pipeline {  
    agent any  
        stages {  
       	    stage("git_checkout") {  
           	    steps {  
              	    echo "cloning repository" 
              	    echo "repo cloned successfully"  
              	    }  
         	    } 
        }
		stage("online 1 book store") {  
           	    steps {  
              	    echo "cloning repository" 
              	    echo "repo cloned successfully"  
            
}
stage("test report") {  
           	    steps {  
              	    echo "cloning repository" 
              	    echo "repo cloned successfully"  
